export default [
    {
      id: 1,
      postedOn: new Date(),
      Jobtitle: "Ase role",
      Branch: "EEE",
      lastdate:'20-march',
      companyName: "Accenture",
      companyUrl: "Accenture.com",
      Jobdescription:'data analyst',
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://accenture.com/careers",
    },
    {
      id: 2,
      postedOn: new Date(),
      Jobtitle: "Embedded software engineer",
      Branch: "CSE",
      lastdate:'20-march',
      companyName: "Nexsemi",
      companyUrl: "nexsemi.com",
      Jobdescription:'data analyst',
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://nexsemi.com/careers",
    },
    {
      id: 3,
      postedOn: new Date(),
      Jobtitle: "Data analyst",
      Branch: "ECE",
      lastdate:'20-march',
      companyName: "Amazon",
      companyUrl: "Amazon.com",
      Jobdescription:'data analyst',
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://amazon.com/careers",
    },
  ];
  